spring.application.name=user-product-api


spring.data.mongodb.uri=mongodb://admin:admin123@localhost:27017/userproductdb?authSource=admin
spring.data.mongodb.database=userproductdb

spring.application.name=user-product-api
server.port=8080

# JWT Configuration
jwt.secret=your-very-long-secret-key-at-least-256-bits-long-for-security
jwt.expiration=86400000
