spring.application.name=user-product-api

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/userproductdb?authSource=admin}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:userproductdb}

server.port=8080

# JWT Configuration
jwt.secret=e4f7b97e6a4f81c79df7d83f9b927bcf2e87e31b7fbb13e2f9048bfa6a26a919
jwt.expiration=86400000



server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=123456
server.ssl.key-alias=mysslkey



